update module

diff --git a/pocket/Bmods b/pocket/Bmods
--- a/pocket/Bmods
+++ b/pocket/Bmods
@@ -3,7 +3,7 @@
 # FileName:     Bmods
 # Author:       8ucchiman
 # CreatedDate:  2023-07-27 13:10:49
-# LastModified: 2023-12-07 17:06:19
+# LastModified: 2023-12-08 12:32:35
 # Reference:    https://unix.stackexchange.com/questions/33255/how-to-define-and-load-your-own-shell-function-in-zsh
 #               https://sig9.org/archives/1120
 #               https://qiita.com/icoxfog417/items/adbbf445d357c924b8fc
@@ -27,6 +27,26 @@ function init () {
     if ! _has nvim; then install_neovim; fi
     if ! _has fzf; then install_fzf; fi
     if ! _has bat; then install_bat; fi
+}
+
+#@
+function lst2issues () {
+    echo $BASE_DIR
+    if [[ ! -e toDolst ]]; then
+        echo "cannot find toDolst"
+        exit 1
+    fi
+    # while read LINE; do
+    #     # echo $LINE
+    #     
+
+    # done< <(cat toDolst)
+    awk '
+        $0 ~ /^-+/  {print $2}
+        $0 ~ /^[ ]+-+/  {print $2}
+    ' toDolst
+    
+
 }
 
 #@
